/*************  history ************
*
*       COMPONENT: JRD  MODULE: UTLSWEP.C
*       generated by Marion V2.5     2/6/90
*       from dev              db        on 10-DEC-1994
*****************************************************************
 * The contents of this file are subject to the Interbase Public
 * License Version 1.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy
 * of the License at http://www.Inprise.com/IPL.html
 *
 * Software distributed under the License is distributed on an
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code was created by Inprise Corporation
 * and its predecessors. Portions created by Inprise Corporation are
 * Copyright (C) Inprise Corporation.
 *
 * All Rights Reserved.
 * Contributor(s): ______________________________________.
*/

/*
 *      PROGRAM:        JRD Access Method
 *      MODULE:         utlswep.c
 *      DESCRIPTION:    UTLS.DLL cleanup functions
 *
 * copyright (c) 1984, 1993 by Borland International
 */

#include <windows.h>
#include "../jrd/common.h"

#ifdef WINDOWS_ONLY

int DLL_EXPORT LOCAL_wep(void)
{
    return 1;
}
#endif
