#!/bin/sh
# The contents of this file are subject to the Interbase Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy
# of the License at http://www.Inprise.com/IPL.html
#
# Software distributed under the License is distributed on an
# "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
# or implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code was created by Inprise Corporation
# and its predecessors. Portions created by Inprise Corporation are
# Copyright (C) Inprise Corporation.
#
# All Rights Reserved.
# Contributor(s): ______________________________________.
# Shell script to setup and build an InterBase kit
if [ $# != 1  ]; then
    echo 'Usage: setup_build {DEV | PROD}'
    exit 1
fi 
cd builds/original
SYSTEM=`cat .platform_type`
# Save the production/development flag
echo "$1" > .version_flag 
./platform $SYSTEM 
cd ../..

